# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d3a6b980b165e65c1a797b398b4760b9bf79d959f2744bb49dda2bc25b974442032850815acc3be157a5b0af9432b4328c290fb8904aef02e9cb48d00e161bd

test:
  secret_key_base: 28f8132e9e6f4f7c382b8d3a18a1dc188d68fa83064f5f052caeb6a1f45cb09494cef4aa7eb1835ba111bcd4afb9135e396619629a0d0fe46a2e5ddb9f5f6e58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
